version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: atsimage
    volumes:
      - ..:/walson_atsapp
    ports:
      - "80:80"
    # tty: true
    # command: sh
    command: node server.js
