version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: atsimage
    volumes:
      - ..:/atsapp
    ports:
      - "80:80"
    command: node server.js
